name: docker

on:
  push:
    branches: 
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mdnice:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: dotnet-exec
      uses: WeihanLi/dotnet-exec-action@3f5683df31bdd46bc989ab088f0d13e5e9edc339
      with:
        script: "./scripts/build.cs"
        options: "--debug"
      env:
        DingBotWebhookUrl: ${{ secrets.DINGBOTWEBHOOKURL }}
          
