name: docker

on:
  push:
    branches: 
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mdnice:latest
        platforms: "linux/amd64,linux/arm64"

    - name: dotnet-exec
      uses: WeihanLi/dotnet-exec-action@0.23.0
      with:
        script: "./scripts/build.cs"
        options: "--debug"
      env:
        DingBotWebhookUrl: ${{ secrets.DINGBOTWEBHOOKURL }}
          
